### ISSUE TITLE
Problem using the DefaultDataState as initial state

### ISSUE THREAD

**Issue by xdma** [nsk90/kstatemachine#24]
I ran into a problem, if I use DefaultDataState as initial state (nested), the machine falls into error, when i change it to regular state (with no data), everything works fine

My data state:
```
    object DialogState1 : DefaultDataState<EmergencyEventData>("Dialog_State_1")
```

Add as initial state (nested):
```
 addInitialState(EmergencyDialogStates.DialogState1) {
                dataTransition<TimeoutEvent, EmergencyEventData> {
                    targetState = EmergencyDialogStates.DialogState2
                }
            }
```

the data event used:
```
class TimeoutEvent(override val data: EmergencyEventData) : DataEvent<EmergencyEventData>
```

Exception when entering the state:
```
2021-10-21 11:09:09.962 E/AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-2
    Process: com.aloecare.hubv2.test, PID: 12584
    java.lang.IllegalStateException: ru.nsk.kstatemachine.BaseStateImpl$StartEvent@22d516f does not contain data required by DialogState1(name=Dialog_State_1)
        at ru.nsk.kstatemachine.DefaultDataState.onDoEnter(DefaultDataState.kt:19)
        at ru.nsk.kstatemachine.BaseStateImpl.doEnter(DefaultDataState.kt:116)
        at ru.nsk.kstatemachine.BaseStateImpl.notifyStateEntry(DefaultDataState.kt:252)
        at ru.nsk.kstatemachine.BaseStateImpl.setCurrentState(DefaultDataState.kt:241)
        at ru.nsk.kstatemachine.BaseStateImpl.recursiveEnterInitialStates(DefaultDataState.kt:178)
        at ru.nsk.kstatemachine.BaseStateImpl.recursiveEnterStatePath(DefaultDataState.kt:190)
        at ru.nsk.kstatemachine.BaseStateImpl.recursiveEnterStatePath(DefaultDataState.kt:196)
        at ru.nsk.kstatemachine.BaseStateImpl.switchToTargetState$kstatemachine(DefaultDataState.kt:272)
        at ru.nsk.kstatemachine.BaseStateImpl.doProcessEvent(DefaultDataState.kt:159)
        at ru.nsk.kstatemachine.StateMachineImpl.processEvent(StateMachineImpl.kt:80)
        at com.aloecare.hubv2.domain.flow.emergency.statemachine.EmergencyStateMachine.processEvent(EmergencyStateMachine.kt:209)
        at com.aloecare.hubv2.domain.base.StateMachineInterface$DefaultImpls.processEvent$default(StateMachineInterface.kt:13)
        at com.aloecare.hubv2.emergency.viewmodel.EmergencyViewModel$processEmergencyEvent$1.invokeSuspend(EmergencyViewModel.kt:450)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

- ver: 0.6.2

**Comment by nsk90** [comment]
I think you've chosen the right solution. Thank you!
